name: nsd
description: Flutter nsd plugin (parent).
version: 1.0.0
homepage: https://github.com/sebastianhaberey/nsd

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  nsd_android: ^1.0.0
  nsd_ios: ^1.0.0
  nsd_macos: ^1.0.0
  nsd_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        default_package: nsd_android
      ios:
        default_package: nsd_ios
      macos:
        default_package: nsd_macos
