name: nsd
description: A Flutter plugin for network service discovery and registration (aka NSD / DNS-SD / Bonjour / mDNS).
version: 1.2.0
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd
issue_tracker: https://github.com/sebastianhaberey/nsd/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

#  # production
#  nsd_android: ^1.0.3
#  nsd_ios: ^1.0.3
#  nsd_macos: ^1.0.3
#  nsd_platform_interface: ^1.2.0

  # development
  nsd_android:
    path: ../nsd_android
  nsd_ios:
    path: ../nsd_ios
  nsd_macos:
    path: ../nsd_macos
  nsd_platform_interface:
    path: ../nsd_platform_interface


dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        default_package: nsd_android
      ios:
        default_package: nsd_ios
      macos:
        default_package: nsd_macos
