name: nsd_example
description: Example application for the Flutter nsd plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ../
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_speed_dial: ^4.4.0+2
  uuid: 3.0.5


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
