name: example
description: Example application stub needed for Android Studio project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd_android:
    path: ../
