# Taken from https://gist.github.com/aagarwal1012/eb2551683d81cf47d60868ab607520b1

name: Android Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run integration tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: nsd/example
    strategy:
      matrix:
        api-level: [21, 30]
        target: [default]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '2.5.3' # you can also specify exact version of flutter

      - name: List all simulators
        run: xcrun xctrace list devices

      - name: Start simulator
        id: simulator
        uses: futureware-tech/simulator-action@v1
        with:
          model: '${{ matrix.device }}'

      - name: Show Flutter configuration
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test --reporter expanded integration_test/nsd_test.dart