# see https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil
# see https://github.com/felangel/bloc/blob/master/.github/workflows/flutter_bloc.yaml
# see https://github.com/ReactiveCircus/android-emulator-runner

name: Android Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "nsd_android/**"
      

env:
  flutter_channel: 'stable' # 'dev', 'alpha', 'stable'
  flutter_version: '2.10.4'
  api_level: '31'
  target: default
  arch: x86_64
  profile: Nexus 6 # "Nexus 4", "Nexus 6", "Nexus 10", "pixel", "pixel_3", "pixel_5"

jobs:
  test:
    name: Run integration tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: nsd/example

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Set up Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api_level }}

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Show Flutter configuration
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api_level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          profile: ${{ env.profile }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: nsd/example
          api-level: ${{ env.api_level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          profile: ${{ env.profile }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: flutter test --no-pub --reporter expanded integration_test/nsd_test.dart
