# see https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil
# see https://github.com/felangel/bloc/blob/master/.github/workflows/flutter_bloc.yaml

name: Windows Tests

on:
  workflow_dispatch: # since nsd_windows is an endorsed plugin, ci is triggered on demand

env:
  flutter_version: '2.10.0'

jobs:
  test:
    name: Run tests (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: nsd/example

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: D:\hostedtoolcache\windows\flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', 'stable'
          flutter-version: ${{ env.flutter_version }}

      - name: Show Flutter configuration
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get
